In [54]:
#importing neccessary libraries
import pandas as pd
import numpy as np

In [55]:
#loading the energy dataset 
df = pd.read_csv("energydata_complete.csv")

In [56]:
#displaying first 5 rows of dataset
df.head()

,date,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,2016-01-11 17:00:00,60,30,19.89,47.596667,19.2,44.790000,19.79,44.730000,19.000000,...,17.033333,45.53,6.600000,733.5,92.0,7.000000,63.000000,5.3,13.275433,13.275433
1,2016-01-11 17:10:00,60,30,19.89,46.693333,19.2,44.722500,19.79,44.790000,19.000000,...,17.066667,45.56,6.483333,733.6,92.0,6.666667,59.166667,5.2,18.606195,18.606195
2,2016-01-11 17:20:00,50,30,19.89,46.300000,19.2,44.626667,19.79,44.933333,18.926667,...,17.000000,45.50,6.366667,733.7,92.0,6.333333,55.333333,5.1,28.642668,28.642668
3,2016-01-11 17:30:00,50,40,19.89,46.066667,19.2,44.590000,19.79,45.000000,18.890000,...,17.000000,45.40,6.250000,733.8,92.0,6.000000,51.500000,5.0,45.410389,45.410389
4,2016-01-11 17:40:00,60,40,19.89,46.333333,19.2,44.530000,19.79,45.000000,18.890000,...,17.000000,45.40,6.133333,733.9,92.0,5.666667,47.666667,4.9,10.084097,10.084097

In [57]:
"""checking the general information of the data like 
 dataset lenght,Number of columns,datatypes of each columns 
"""
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19735 entries, 0 to 19734
Data columns (total 29 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         19735 non-null  object
 1   Appliances   19735 non-null  int64
 2   lights       19735 non-null  int64
 3   T1           19735 non-null  float64
 4   RH_1         19735 non-null  float64
 5   T2           19735 non-null  float64
 6   RH_2         19735 non-null  float64
 7   T3           19735 non-null  float64
 8   RH_3         19735 non-null  float64
 9   T4           19735 non-null  float64
 10  RH_4         19735 non-null  float64
 11  T5           19735 non-null  float64
 12  RH_5         19735 non-null  float64
 13  T6           19735 non-null  float64
 14  RH_6         19735 non-null  float64
 15  T7           19735 non-null  float64
 16  RH_7         19735 non-null  float64
 17  T8           19735 non-null  float64
 18  RH_8         19735 non-null  float64
 19  T9           19735 non-null  float64
 20  RH_9         19735 non-null  float64
 21  T_out        19735 non-null  float64
 22  Press_mm_hg  19735 non-null  float64
 23  RH_out       19735 non-null  float64
 24  Windspeed    19735 non-null  float64
 25  Visibility   19735 non-null  float64
 26  Tdewpoint    19735 non-null  float64
 27  rv1          19735 non-null  float64
 28  rv2          19735 non-null  float64
dtypes: float64(26), int64(2), object(1)
memory usage: 4.4+ MB

In [58]:
#Check Missing values
'''
This function calculates the feature with the missing values,
Total number of nans
percentage of the missing values in dataset

'''
def Missing_Values(df):
    Missing_Data=df.isnull().sum().reset_index().rename(columns={'index':'Fuel_label',0:'Missing_Values'})
    Feature_Value=Missing_Data[Missing_Data['Missing_Values']==Missing_Data['Missing_Values'].max()]['Fuel_label'].tolist()[0]
    Total_Value=Missing_Data[Missing_Data['Missing_Values']==Missing_Data['Missing_Values'].max()]['Missing_Values'].tolist()[0]
    Percent_Value=100*(Missing_Data[Missing_Data['Missing_Values']==Missing_Data['Missing_Values'].max()]['Missing_Values'].tolist()[0]/len(df))
    print('Feature:',Feature_Value ,',', f'Total:{Total_Value:.3f}',',',f'Percent:{Percent_Value:.3f}')

Missing_Values(df)

Feature: date , Total:0.000 , Percent:0.000

In [59]:
#dropping some columns Lights and date
df = df.drop(columns=['lights', 'date'])

In [60]:
#Checking the above columns if it was dropped
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19735 entries, 0 to 19734
Data columns (total 27 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Appliances   19735 non-null  int64
 1   T1           19735 non-null  float64
 2   RH_1         19735 non-null  float64
 3   T2           19735 non-null  float64
 4   RH_2         19735 non-null  float64
 5   T3           19735 non-null  float64
 6   RH_3         19735 non-null  float64
 7   T4           19735 non-null  float64
 8   RH_4         19735 non-null  float64
 9   T5           19735 non-null  float64
 10  RH_5         19735 non-null  float64
 11  T6           19735 non-null  float64
 12  RH_6         19735 non-null  float64
 13  T7           19735 non-null  float64
 14  RH_7         19735 non-null  float64
 15  T8           19735 non-null  float64
 16  RH_8         19735 non-null  float64
 17  T9           19735 non-null  float64
 18  RH_9         19735 non-null  float64
 19  T_out        19735 non-null  float64
 20  Press_mm_hg  19735 non-null  float64
 21  RH_out       19735 non-null  float64
 22  Windspeed    19735 non-null  float64
 23  Visibility   19735 non-null  float64
 24  Tdewpoint    19735 non-null  float64
 25  rv1          19735 non-null  float64
 26  rv2          19735 non-null  float64
dtypes: float64(26), int64(1)
memory usage: 4.1 MB

In [61]:
#import MinMaxScaler for scaling the dataset
'''
This ensures the dataset is well scaled.
'''
from sklearn.preprocessing import MinMaxScaler
sc= MinMaxScaler()
df_normalized= pd.DataFrame(sc.fit_transform(df), columns = df.columns)

In [62]:
#Getting and Droping the target varriable
'''
    Here we separate the target(Appliances) from the rest varriables
'''
X =df_normalized.drop(columns=['Appliances'])
y =df_normalized['Appliances']

In [63]:
#Now, we split our dataset into the training and testing dataset.
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y,test_size=0.3, random_state=42)

In [64]:
#Creating the Linear multiple Linear regression Model
from sklearn.linear_model import LinearRegression
linear_model = LinearRegression()

In [65]:
#fitting the model to the training Dataset
linear_model.fit(x_train, y_train)
#obtaining predictions
predicted_values = linear_model.predict(x_test)

In [66]:
#Question 13
#MAE
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test, predicted_values)
round(mae, 2)

0.05

In [67]:
type(predicted_values)

numpy.ndarray

In [68]:
type(y_test)

pandas.core.series.Series

In [69]:
y_test=np.array(y_test)

In [70]:
#Question 14
rss = np.sum(np.square(y_test-predicted_values))
round(rss,2)

45.35

In [71]:
#Question 15
from sklearn.metrics import mean_squared_error
rmse = np.sqrt(mean_squared_error(y_test, predicted_values))
round(rmse, 2)

0.09

In [72]:
from sklearn.metrics import r2_score
r2_score = r2_score(y_test, predicted_values)
round(r2_score, 2)

0.15

In [73]:
def get_weights_df(model, feat, col_name):
#this function returns the weight of every feature
    weights = pd.Series(model.coef_, feat.columns).sort_values()
    weights_df = pd.DataFrame(weights).reset_index()
    weights_df.columns = ['Features', col_name]
    weights_df[col_name].round(3)
    return weights_df
linear_model_weights = get_weights_df(linear_model, x_train, 'Linear_Model_Weight')

In [74]:
linear_model_weights

       Features  Linear_Model_Weight
0          RH_2            -0.456698
1         T_out            -0.321860
2            T2            -0.236178
3            T9            -0.189941
4          RH_8            -0.157595
5        RH_out            -0.077671
6          RH_7            -0.044614
7          RH_9            -0.039800
8            T5            -0.015657
9            T1            -0.003281
10          rv2             0.000770
11          rv1             0.000770
12  Press_mm_hg             0.006839
13           T7             0.010319
14   Visibility             0.012307
15         RH_5             0.016006
16         RH_4             0.026386
17           T4             0.028981
18    Windspeed             0.029183
19         RH_6             0.038049
20         RH_3             0.096048
21           T8             0.101995
22    Tdewpoint             0.117758
23           T6             0.236425
24           T3             0.290627
25         RH_1             0.553547

In [75]:
#Question 16
linear_model_weights.sort_values(by='Linear_Model_Weight',inplace=True)

In [76]:
linear_model_weights

       Features  Linear_Model_Weight
0          RH_2            -0.456698
1         T_out            -0.321860
2            T2            -0.236178
3            T9            -0.189941
4          RH_8            -0.157595
5        RH_out            -0.077671
6          RH_7            -0.044614
7          RH_9            -0.039800
8            T5            -0.015657
9            T1            -0.003281
10          rv2             0.000770
11          rv1             0.000770
12  Press_mm_hg             0.006839
13           T7             0.010319
14   Visibility             0.012307
15         RH_5             0.016006
16         RH_4             0.026386
17           T4             0.028981
18    Windspeed             0.029183
19         RH_6             0.038049
20         RH_3             0.096048
21           T8             0.101995
22    Tdewpoint             0.117758
23           T6             0.236425
24           T3             0.290627
25         RH_1             0.553547

In [77]:
from sklearn.linear_model import Ridge
ridge_reg = Ridge(alpha=0.4)
ridge_reg.fit(x_train, y_train)
#obtain predictions
predicted_values_ridge = ridge_reg.predict(x_test)

In [78]:
from sklearn.metrics import mean_squared_error
rmse = np.sqrt(mean_squared_error(y_test, predicted_values_ridge))
round(rmse, 3)

0.088

In [79]:
ridge_weights_df = get_weights_df(ridge_reg, x_train, 'Ridge_Weight')

In [80]:
ridge_weights_df

       Features  Ridge_Weight
0          RH_2     -0.411071
1         T_out     -0.262172
2            T2     -0.201397
3            T9     -0.188916
4          RH_8     -0.156830
5        RH_out     -0.054724
6          RH_7     -0.045977
7          RH_9     -0.041367
8            T5     -0.019853
9            T1     -0.018406
10          rv1      0.000748
11          rv2      0.000748
12  Press_mm_hg      0.006584
13           T7      0.010098
14   Visibility      0.012076
15         RH_5      0.016152
16         RH_4      0.024579
17           T4      0.027384
18    Windspeed      0.030268
19         RH_6      0.035519
20    Tdewpoint      0.083128
21         RH_3      0.095135
22           T8      0.101028
23           T6      0.217292
24           T3      0.288087
25         RH_1      0.519525

In [81]:
from sklearn.linear_model import Ridge
ridge_reg2 = Ridge(alpha=0.001)
ridge_reg2.fit(x_train, y_train)
#obtain predictions
predicted_values_ridge = ridge_reg2.predict(x_test)

In [82]:
ridge_weights_df = get_weights_df(ridge_reg2, x_train, 'Ridge_Weight')

In [83]:
ridge_weights_df

       Features  Ridge_Weight
0          RH_2     -0.456570
1         T_out     -0.321674
2            T2     -0.236080
3            T9     -0.189939
4          RH_8     -0.157594
5        RH_out     -0.077597
6          RH_7     -0.044617
7          RH_9     -0.039805
8            T5     -0.015669
9            T1     -0.003325
10          rv1      0.000770
11          rv2      0.000770
12  Press_mm_hg      0.006839
13           T7      0.010318
14   Visibility      0.012306
15         RH_5      0.016006
16         RH_4      0.026381
17           T4      0.028977
18    Windspeed      0.029187
19         RH_6      0.038041
20         RH_3      0.096045
21           T8      0.101993
22    Tdewpoint      0.117648
23           T6      0.236369
24           T3      0.290621
25         RH_1      0.553453

In [84]:
from sklearn.linear_model import Lasso
lasso_reg = Lasso(alpha = 0.001)
lasso_reg.fit(x_train, y_train)

predicted_values_lasso = lasso_reg.predict(x_test)

from sklearn.metrics import mean_squared_error
rmse = np.sqrt(mean_squared_error(y_test, predicted_values_lasso))
round(rmse, 3)

0.094

In [51]:
lasso_weights_df = get_weights_df(lasso_reg, x_train, 'Lasso_weight')

In [52]:
lasso_weights_df

       Features  Lasso_weight
0        RH_out     -0.049557
1          RH_8     -0.000110
2            T1      0.000000
3     Tdewpoint      0.000000
4    Visibility      0.000000
5   Press_mm_hg     -0.000000
6         T_out      0.000000
7          RH_9     -0.000000
8            T9     -0.000000
9            T8      0.000000
10         RH_7     -0.000000
11          rv1     -0.000000
12           T7     -0.000000
13           T6      0.000000
14         RH_5      0.000000
15           T5     -0.000000
16         RH_4      0.000000
17           T4     -0.000000
18         RH_3      0.000000
19           T3      0.000000
20         RH_2     -0.000000
21           T2      0.000000
22         RH_6     -0.000000
23          rv2     -0.000000
24    Windspeed      0.002912
25         RH_1      0.017880

In [56]:
final_weights = pd.merge(linear_model_weights, ridge_weights_df, on='Features')
final_weights = pd.merge(final_weights, lasso_weights_df, on='Features')

In [57]:
final_weights

       Features  Linear_Model_Weight  Ridge_Weight  Lasso_weight
0          RH_2            -0.456698     -0.456570     -0.000000
1         T_out            -0.321860     -0.321674      0.000000
2            T2            -0.236178     -0.236080      0.000000
3            T9            -0.189941     -0.189939     -0.000000
4          RH_8            -0.157595     -0.157594     -0.000110
5        RH_out            -0.077671     -0.077597     -0.049557
6          RH_7            -0.044614     -0.044617     -0.000000
7          RH_9            -0.039800     -0.039805     -0.000000
8            T5            -0.015657     -0.015669     -0.000000
9            T1            -0.003281     -0.003325      0.000000
10          rv2             0.000770      0.000770     -0.000000
11          rv1             0.000770      0.000770     -0.000000
12  Press_mm_hg             0.006839      0.006839     -0.000000
13           T7             0.010319      0.010318     -0.000000
14   Visibility             0.012307      0.012306      0.000000
15         RH_5             0.016006      0.016006      0.000000
16         RH_4             0.026386      0.026381      0.000000
17           T4             0.028981      0.028977     -0.000000
18    Windspeed             0.029183      0.029187      0.002912
19         RH_6             0.038049      0.038041     -0.000000
20         RH_3             0.096048      0.096045      0.000000
21           T8             0.101995      0.101993      0.000000
22    Tdewpoint             0.117758      0.117648      0.000000
23           T6             0.236425      0.236369      0.000000
24           T3             0.290627      0.290621      0.000000
25         RH_1             0.553547      0.553453      0.017880

In [1]:
#Question 11
import pandas as pd
import numpy as np

In [2]:
#loading the energy dataset 
df = pd.read_csv("energydata_complete.csv")

In [3]:
df = df.drop(columns=['date', 'lights'])

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19735 entries, 0 to 19734
Data columns (total 27 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Appliances   19735 non-null  int64
 1   T1           19735 non-null  float64
 2   RH_1         19735 non-null  float64
 3   T2           19735 non-null  float64
 4   RH_2         19735 non-null  float64
 5   T3           19735 non-null  float64
 6   RH_3         19735 non-null  float64
 7   T4           19735 non-null  float64
 8   RH_4         19735 non-null  float64
 9   T5           19735 non-null  float64
 10  RH_5         19735 non-null  float64
 11  T6           19735 non-null  float64
 12  RH_6         19735 non-null  float64
 13  T7           19735 non-null  float64
 14  RH_7         19735 non-null  float64
 15  T8           19735 non-null  float64
 16  RH_8         19735 non-null  float64
 17  T9           19735 non-null  float64
 18  RH_9         19735 non-null  float64
 19  T_out        19735 non-null  float64
 20  Press_mm_hg  19735 non-null  float64
 21  RH_out       19735 non-null  float64
 22  Windspeed    19735 non-null  float64
 23  Visibility   19735 non-null  float64
 24  Tdewpoint    19735 non-null  float64
 25  rv1          19735 non-null  float64
 26  rv2          19735 non-null  float64
dtypes: float64(26), int64(1)
memory usage: 4.1 MB

In [5]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
normalised_df = pd.DataFrame(scaler.fit_transform(df), columns = df.columns)
X = normalised_df[['T2']]
y = normalised_df[['T6']]

In [6]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=0.3, random_state=42)
from sklearn.linear_model import LinearRegression
linear_model = LinearRegression()
linear_model.fit(x_train, y_train)

predicted_values = linear_model.predict(x_test)

In [7]:
Question 11
from sklearn.metrics import r2_score
r2_score = r2_score(y_test, predicted_values)
round(r2_score, 2)

0.64